name: Build, Test and Deploy Frontend and Backend

on:
  push:
    branches: [main]

jobs:
  deploy_backend:
    name: Deploy Backend to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install
        working-directory: back

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: back

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install
        working-directory: front

      - name: Build Project
        run: npm run build
        working-directory: front

      - name: Prepare Deployment
        run: |
          mkdir -p deploy-root
          cp -r front/dist/* deploy-root/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: deploy-root

  deploy_frontend:
    name: Deploy Frontend to GitHub Pages
    needs: build_frontend
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
