name: Build, Test and Deploy Frontend and Backend

on:
  push:
    branches: [main]

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: back

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: back

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: front

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: npm run build
        working-directory: front

      - name: Prepare deployment artifact
        run: |
          mkdir -p deploy-root
          cp -r front/dist/inscription-projet-group/browser/* deploy-root/
      - name: Upload deployment artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: deploy-root

  deploy_to_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_frontend

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
