name: Build, Test and Deploy Frontend

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_and_test_frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: front

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: npm run build
        working-directory: front

      - name: Start Angular server
        run: npm start &
        working-directory: front

      - name: Wait for Angular server to start
        run: sleep 20

      - name: Install Cypress
        run: npm install cypress --save-dev
        working-directory: front

      - name: Run Cypress tests with mocks
        run: npx cypress run
        working-directory: front

      - name: Prepare deployment artifact
        run: |
          mkdir -p deploy-root
          cp -r front/dist/inscription-projet-group/browser/* deploy-root/
          
      - name: Upload deployment artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy-root

  deploy_to_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_and_test_frontend

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
